{
 "title": "Internet - Elevalink - speedtest_grafana",
 "description": "O dashboard monitora o link de internet contratado do provedor Elevalink.",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Link Internet - Elevalink",
   "type": "stat",
   "description": "Monitora se o link de internet esta Up ou Down.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Link Internet" },
     "host": { "filter": "link internet - Elevalink" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "component: network" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "PROVEDOR",
   "type": "stat",
   "description": "Esse painel mostra o nome do provedor de acesso a internet contratado.",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "dataset": "speedtest_grafana",
     "rawSql": "SELECT DISTINCT provider FROM speedtest_grafana.speedtest_results;"
    }
   ]
  },
  { "title": "MÉDIA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "DOWNLOAD",
   "type": "gauge",
   "description": "Esse painel mostra a média de download do dia atual.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "dataset": "speedtest_data",
     "rawSql": "SELECT \n    AVG(download) AS media_download\nFROM \n    speedtest_grafana.speedtest_results\nWHERE \n    timestamp >= CURDATE()\n    AND timestamp < CURDATE() + INTERVAL 1 DAY;"
    }
   ]
  },
  {
   "title": "UPLOAD",
   "type": "gauge",
   "description": "Esse painel mostra a média de upload do dia atual.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "dataset": "speedtest_data",
     "rawSql": "SELECT \n    AVG(upload) AS media_upload\nFROM \n    speedtest_grafana.speedtest_results\nWHERE \n    timestamp >= CURDATE()\n    AND timestamp < CURDATE() + INTERVAL 1 DAY;\n"
    }
   ]
  },
  {
   "title": "PING",
   "type": "gauge",
   "description": "Esse painel mostra a média do ping do dia atual.\n\nPara jogos o aconselhado é uma latência abaixo de 20 ms.\nPara navegar normalmente na web, abaixo de 100 ms é um bom valor.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "speedtest_data",
     "rawSql": "SELECT \n    AVG(ping) AS media_ping\nFROM \n    speedtest_grafana.speedtest_results\nWHERE \n    timestamp >= CURDATE()\n    AND timestamp < CURDATE() + INTERVAL 1 DAY;\n"
    }
   ]
  },
  {
   "title": "RESULTADO DO ÚLTIMO TESTE",
   "type": "dalvany-image-panel",
   "description": "Esse painel mostra a imagem do último teste feito pelo speedtest.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "dataset": "speedtest_grafana",
     "rawSql": "SELECT \n    url,\n    timestamp\nFROM\n    speedtest_grafana.speedtest_results\nORDER BY\n    timestamp\nDESC LIMIT 1;  -- Limita para a última imagem inserida, se desejar"
    }
   ]
  },
  { "title": "GRANULARIDADE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "VELOCIDADE DE DOWNLOAD",
   "type": "timeseries",
   "description": "Esse painel mostra o teste de Download pelo SpeedTest a cada 5 minutos configurado na cron do servidor \"Proxmox\".\n\nA Velocidade de download se refere à rapidez com que um arquivo pode ser baixado de um serviço na Internet. Respeitando-se as boas práticas de uso do medidor, os resultados devem ser muito próximos ao valores anunciados por seu provedor de Internet.\n\nSegundo resolução da Anatel, deve-se garantir um valor médio acima de 80% do valor contratado. Mas, caso os resultados persistam abaixo de 40% do valor contratado após diversas medições, você pode cobrar providências junto ao seu provedor.",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "dataset": "speedtest_data",
     "rawSql": "SELECT\n  CONVERT_TZ(timestamp, '-03:00', '+00:00') AS time,\n  download\nFROM\n  speedtest_grafana.speedtest_results\nWHERE\n  $__timeFilter(timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "MÉDIA GRANULAR",
   "type": "gauge",
   "description": "Esse painel mostra a média granular de download.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "speedtest_data",
     "rawSql": "SELECT\n  AVG(download) AS media_download\nFROM\n  speedtest_grafana.speedtest_results\nWHERE\n  $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "VELOCIDADE DE UPLOAD",
   "type": "timeseries",
   "description": "Esse painel mostra o teste de Upload pelo SpeedTest a cada 5 minutos configurado na cron do servidor \"Proxmox\".\n\nA Velocidade de upload se refere à rapidez com que um arquivo pode ser enviado a um serviço na Internet. Esse valor costuma ser inferior à velocidade de download, e também deveria estar descrito no contrato com seu provedor de Internet.\n\nAs mesmas regras sobre utilização do medidor e resultados descritas sobre a velocidade de download valem para o teste de upload.",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "dataset": "speedtest_data",
     "rawSql": "SELECT\n  CONVERT_TZ(timestamp, '-03:00', '+00:00') AS time,\n  upload\nFROM\n  speedtest_grafana.speedtest_results\nWHERE\n  $__timeFilter(timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "MÉDIA GRANULAR",
   "type": "gauge",
   "description": "Esse painel mostra a média granular de upload.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "speedtest_data",
     "rawSql": "SELECT\n  AVG(upload) AS media_upload\nFROM\n  speedtest_grafana.speedtest_results\nWHERE\n  $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "LATÊNCIA / PING",
   "type": "timeseries",
   "description": "Esse painel mostra o teste de Latência (Ping) pelo SpeedTest a cada 5 minutos configurado na cron do servidor \"Proxmox\".\n\nO Ping ou latência bidirecional é a medida de tempo para uma mensagem ir a um destino e voltar. Um valor alto afeta principalmente a qualidade da navegação na Web, em jogos on-line e em conversas com transmissão de voz e imagem em vídeo.\n\nPara jogos o aconselhado é uma latência abaixo de 20 ms. Para navegar normalmente na web, abaixo de 100 ms é um bom valor.",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "speedtest_data",
     "rawSql": "SELECT\n  CONVERT_TZ(timestamp, '-03:00', '+00:00') AS time,\n  ping\nFROM\n  speedtest_grafana.speedtest_results\nWHERE\n  $__timeFilter(timestamp)\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "MÉDIA GRANULAR",
   "type": "gauge",
   "description": "Esse painel mostra a média granular do ping.\n\nPara jogos o aconselhado é uma latência abaixo de 20 ms.\nPara navegar normalmente na web, abaixo de 100 ms é um bom valor.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "speedtest_data",
     "rawSql": "SELECT\n  AVG(ping) AS media_ping\nFROM\n  speedtest_grafana.speedtest_results\nWHERE\n  $__timeFilter(timestamp);\n"
    }
   ]
  },
  { "title": "ERROR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "ERROR NOS TESTES",
   "type": "timeseries",
   "description": "Esse painel mostra o gráfico de erros categorizado pelo tipo de erro mapeado ou não executado pelo SpeedTest a cada 5 minutos configurado na cron do servidor \"Proxmox\".",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 42 },
   "targets": [
    {
     "dataset": "speedtest_grafana",
     "rawSql": "SELECT\n  CONVERT_TZ(timestamp, '-03:00', '+00:00') AS time,\n  CASE\n    WHEN error_message LIKE '%Unable to connect to servers to test latency%' THEN 1\n    WHEN error_message LIKE '%HTTP Error 403: Forbidden%' THEN 2\n    WHEN error_message LIKE '%urlopen error [Errno -2] Name or service not known%' THEN 3\n    WHEN error_message LIKE '%The read operation timed out%' THEN 4\n    WHEN error_message LIKE '%urlopen error [Errno -3] Temporary failure in name resolution%' THEN 5\n    WHEN error_message LIKE '%Could not submit results to speedtest.net%' THEN 6\n    WHEN error_message LIKE '%urlopen error timed out%' THEN 7\n    WHEN error_message LIKE '%HTTP Error 503: Service Unavailable%' THEN 8\n    WHEN error_message LIKE '%HTTP Error 520%' THEN 9\n    WHEN error_message LIKE '%HTTP Error 429: Too Many Requests%' THEN 10\n    WHEN error_message LIKE '%urlopen error [Errno 104] Connection reset by peer%' THEN 11\n    WHEN error_message LIKE '%HTTP Error 500: Internal Server Error%' THEN 12\n    WHEN error_message LIKE '%urlopen error _ssl.c:1012: The handshake operation timed out%' THEN 13\n    WHEN error_message LIKE '%Remote end closed connection without response%' THEN 14\n    ELSE 15\n  END AS valor_erro,\n  CASE\n    WHEN error_message LIKE '%Unable to connect to servers to test latency%' THEN 'Unable to connect to servers to test latency'\n    WHEN error_message LIKE '%HTTP Error 403: Forbidden%' THEN 'HTTP Error 403: Forbidden'\n    WHEN error_message LIKE '%urlopen error [Errno -2] Name or service not known%' THEN 'urlopen error [Errno -2] Name or service not known'\n    WHEN error_message LIKE '%The read operation timed out%' THEN 'The read operation timed out'\n    WHEN error_message LIKE '%urlopen error [Errno -3] Temporary failure in name resolution%' THEN 'urlopen error [Errno -3] Temporary failure in name resolution'\n    WHEN error_message LIKE '%Could not submit results to speedtest.net%' THEN 'Could not submit results to speedtest.net'\n    WHEN error_message LIKE '%urlopen error timed out%' THEN 'urlopen error timed out'\n    WHEN error_message LIKE '%HTTP Error 503: Service Unavailable%' THEN 'HTTP Error 503: Service Unavailable'\n    WHEN error_message LIKE '%HTTP Error 520%' THEN 'HTTP Error 520'\n    WHEN error_message LIKE '%HTTP Error 429: Too Many Requests%' THEN 'HTTP Error 429: Too Many Requests'\n    WHEN error_message LIKE '%urlopen error [Errno 104] Connection reset by peer%' THEN 'urlopen error [Errno 104] Connection reset by peer'\n    WHEN error_message LIKE '%HTTP Error 500: Internal Server Error%' THEN 'HTTP Error 500: Internal Server Error'\n    WHEN error_message LIKE '%urlopen error _ssl.c:1012: The handshake operation timed out%' THEN 'urlopen error _ssl.c:1012: The handshake operation timed out'\n    WHEN error_message LIKE '%Remote end closed connection without response%' THEN 'Remote end closed connection without response'\n    ELSE 'Erro Not Mapped'\n  END AS erros\nFROM\n  speedtest_grafana.speedtest_errors\nWHERE\n  $__timeFilter(timestamp)\nORDER BY\n  time ASC;"
    }
   ]
  },
  {
   "title": "LISTA DE ERRO NO TESTE :: DIA ATUAL",
   "type": "logs",
   "description": "Esse painel mostra a lista de erros do dia atual na saída de erro (stderr) executado pelo SpeedTest a cada 5 minutos configurado na cron do servidor \"Proxmox\".",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 42 },
   "targets": [
    {
     "dataset": "speedtest_grafana",
     "rawSql": "SELECT\n  error_message,\n  CONVERT_TZ(timestamp, '-03:00', '+00:00') AS time\nFROM speedtest_grafana.speedtest_errors\nWHERE\n  error_message <> ''\n  AND timestamp >= CURDATE()\n  AND timestamp < CURDATE() + INTERVAL 1 DAY\nORDER BY time ASC;"
    }
   ]
  },
  { "title": "ANÁLISE GEOGRÁFICA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "DISTÂNCIA DOS SERVIDORES",
   "type": "timeseries",
   "description": "Esse gráico mostrar a distância dos servidores onde o teste foi executado pelo SpeedTest a cada 5 minutos configurado na cron do servidor \"Proxmox\".",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 52 },
   "targets": [
    {
     "dataset": "speedtest_data",
     "rawSql": "SELECT\n  distance,\n  CONVERT_TZ(timestamp, '-03:00', '+00:00') AS time\nFROM\n  speedtest_grafana.speedtest_results\nWHERE\n  $__timeFilter(timestamp)\nORDER BY\n  time ASC;"
    }
   ]
  },
  {
   "title": "LOCAL DOS TESTES :: DIA ATUAL",
   "type": "table",
   "description": "Esse painel mostra o nome do servidor e da cidade que fez os testes no dia atual.",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 52 },
   "targets": [
    {
     "dataset": "speedtest_data",
     "rawSql": "SELECT\n  city,\n  server,\n  CONVERT_TZ(timestamp, '-03:00', '+00:00') AS time\nFROM\n  speedtest_grafana.speedtest_results\nWHERE\n  timestamp >= CURDATE()\n  AND timestamp < CURDATE() + INTERVAL 1 DAY\nORDER BY time DESC;"
    }
   ]
  },
  {
   "title": "QNT DE TESTE POR CIDADE :: DIA ATUAL",
   "type": "piechart",
   "description": "Esse painel mostra a quantidade de vezes que uma cidade fez o teste no dia atual.",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "speedtest_data",
     "rawSql": "SELECT \n    city,\n    COUNT(*) AS test_count\nFROM \n    speedtest_grafana.speedtest_results\nWHERE \n    timestamp >= CURDATE()\n    AND timestamp < CURDATE() + INTERVAL 1 DAY\nGROUP BY \n    city\nORDER BY \n    test_count DESC;\n"
    }
   ]
  },
  {
   "title": "QNT DE TESTE POR SERVIDOR :: DIA ATUAL",
   "type": "bargauge",
   "description": "O painel mostra a lista da quantidade de testes por servidor realizados no dia atual, em ordem decrescente de testes.",
   "gridPos": { "h": 12, "w": 10, "x": 7, "y": 62 },
   "targets": [
    {
     "dataset": "speedtest_grafana",
     "rawSql": "SELECT\n    Servidor,\n    teste_count\nFROM\n    (\n        SELECT\n            server AS Servidor,\n            COUNT(*) AS teste_count\n        FROM\n            speedtest_grafana.speedtest_results\n        WHERE\n            timestamp >= CURDATE()\n            AND timestamp < CURDATE() + INTERVAL 1 DAY\n        GROUP BY\n            server\n        ORDER BY\n            teste_count DESC\n    ) AS top_servers\nORDER BY\n    teste_count DESC;\n"
    }
   ]
  },
  {
   "title": "CIDADES MAIS DISTANTES :: DIA ATUAL",
   "type": "bargauge",
   "description": "Esse painel mostra as cidade mais distantes em quilômetros onde foi feita o teste no dia atual.",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 62 },
   "targets": [
    {
     "dataset": "speedtest_data",
     "rawSql": "SELECT\n  city,\n  MAX(distance) AS km\nFROM\n  speedtest_grafana.speedtest_results\nWHERE\n  timestamp >= CURDATE()\n  AND timestamp < CURDATE() + INTERVAL 1 DAY\nGROUP BY\n  city\nORDER BY\n  km DESC;"
    }
   ]
  }
 ]
}